include("08.jl")
using Test

example_input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

@testset "prepare_input" begin
    @test prepare_input(example_input) == Map((12, 12), Dict(
        '0' => [(9, 2), (6, 3), (8, 4), (5, 5)],
        'A' => [(7, 6), (9, 9), (10, 10)]
    ))
end

@testset "find_antinode_positions" begin
    input_with_two_antennas = """
        ..........
        ...#......
        ..........
        ....a.....
        ..........
        .....a....
        ..........
        ......#...
        ..........
        .........."""
    @test find_antinode_positions(prepare_input(input_with_two_antennas)) == Set([(4, 2), (7, 8)])
    input_with_three_antennas = """
        ..........
        ...#......
        #.........
        ....a.....
        ........a.
        .....a....
        ..#.......
        ......A...
        ..........
        .........."""
    @test find_antinode_positions(prepare_input(input_with_three_antennas)) == Set([(4, 2), (1, 3), (3, 7), (7, 8)])
    @test find_antinode_positions(prepare_input(example_input)) == Set([(7, 1), (12, 1), (4, 2), (5, 3), (11, 3), (3, 4), (10, 5), (2, 6), (7, 6), (4, 7), (1, 8), (8, 8), (11, 11), (11, 12)])
end

@testset "Example Input" begin
    input = prepare_input(example_input)
    @test part1(input) === 14
    @test part2(input) === 34
end

@testset "Real input" begin
    input = prepare_input(get_input(day=8, year=2024))
    @test part1(input) === 396
    @test part2(input) === 1200
end